# Generated by Django 2.2.12 on 2022-01-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='book',
        ),
    ]
