# Generated by Django 2.2.12 on 2022-01-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='notes',
        ),
    ]
